import {useEffect,useState} from "react";
import {api} from "../api";

type SystemInfo={version:string;library_path?:string;available:boolean;writable:boolean;message:string};
const defaults=["要約","研究方法・条件","主な結果","評価・疑問","自分の研究への活用","関連文献"];

export default function SettingsPage({system,readonly,refresh}:{system:SystemInfo;readonly:boolean;refresh:()=>void}){
 const [sections,setSections]=useState<string[]>(defaults);const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{api<{content:string}>("/settings/template").then(value=>setSections([...value.content.matchAll(/^## (.+)$/gm)].map(match=>match[1]))).catch(()=>{});},[]);
 async function action(path:string,body?:unknown){setBusy(true);setMessage("");setError("");try{const value=await api<Record<string,unknown>>(path,{method:"POST",body:body?JSON.stringify(body):undefined});setMessage(String(value.message||value.path||`完了しました。${value.indexed!==undefined?` ${value.indexed}件を索引化しました。`:""}`));refresh();}catch(cause){setError(cause instanceof Error?cause.message:"処理に失敗しました。");}finally{setBusy(false);}}
 async function saveTemplate(){try{await api("/settings/template",{method:"PUT",body:JSON.stringify({sections})});setMessage("メモテンプレートを保存しました。既存メモは変更していません。");}catch(cause){setError(cause instanceof Error?cause.message:"保存に失敗しました。");}}
 return <main className="page"><header className="page-header"><div><p className="eyebrow">Settings</p><h1>設定</h1><p className="muted">データの所在と復元手段を、いつでも確認できます。</p></div><strong>LitWeave v{system.version}</strong></header>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}{busy&&<div className="progress"><span/></div>}
  <div className="detail-grid"><section className="panel stack"><h2>ライブラリ</h2><label>Box Drive保存先<input readOnly value={system.library_path||""}/></label><p>{system.available?"利用可能":"利用できません"} / {system.writable?"書き込み可能":"読み取り専用"}</p><small className="muted">{system.message}</small><button className="secondary" disabled={busy} onClick={()=>action("/maintenance/rebuild")}>SQLite索引を再構築</button><button disabled={readonly||busy} onClick={()=>action("/maintenance/backup")}>軽量バックアップを作成</button><div className="actions"><button className="secondary" disabled={readonly||busy} onClick={()=>action("/maintenance/export/csv")}>CSV出力</button><button className="secondary" disabled={readonly||busy} onClick={()=>action("/maintenance/export/json")}>JSON出力</button><button className="secondary" disabled={readonly||busy} onClick={()=>action("/maintenance/export/markdown")}>Markdown出力</button></div></section>
  <section className="panel stack"><h2>メモテンプレート</h2><p className="muted">変更は新しく登録する論文だけに適用されます。</p>{sections.map((value,index)=><div className="actions" style={{margin:0}} key={index}><input aria-label={`セクション${index+1}`} value={value} onChange={e=>setSections(sections.map((item,i)=>i===index?e.target.value:item))}/><button className="secondary" disabled={index===0} onClick={()=>{const next=[...sections];[next[index-1],next[index]]=[next[index],next[index-1]];setSections(next);}}>↑</button><button className="secondary" disabled={index===sections.length-1} onClick={()=>{const next=[...sections];[next[index+1],next[index]]=[next[index],next[index+1]];setSections(next);}}>↓</button><button className="danger" onClick={()=>setSections(sections.filter((_,i)=>i!==index))}>削除</button></div>)}<button className="secondary" onClick={()=>setSections([...sections,"新しいセクション"])}>セクションを追加</button><button className="secondary" onClick={()=>setSections(defaults)}>既定に戻す</button><button disabled={readonly} onClick={saveTemplate}>テンプレートを保存</button></section></div>
 </main>;
}
